"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""Add ForeignKey to token_refresh.usuario_id (MELHORIA-14)

Revision ID: c9d8e7f6a5b4
Revises: f3c2b8a1d4e6
Create Date: 2026-08-03 09:00:00.000000

token_refresh.usuario_id era indexado mas sem ForeignKey — nada impedia um
registro órfão (usuario_id inexistente), mesmo com PRAGMA foreign_keys=ON,
porque a constraint simplesmente não existia. Cascade em DELETE porque a
exclusão de usuário no sistema é lógica (soft delete via `ativo=False`); a
constraint só entra em ação se um dia existir hard-delete.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d8e7f6a5b4'
down_revision: Union[str, None] = 'f3c2b8a1d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_refresh', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_token_refresh_usuario_id', 'usuarios', ['usuario_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_refresh', schema=None) as batch_op:
        batch_op.drop_constraint('fk_token_refresh_usuario_id', type_='foreignkey')

    # ### end Alembic commands ###
