"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add persistent trigrama fields to inspections

Revision ID: f997d1a99b6e
Revises: 617ffa2f1b86
Create Date: 2026-05-02 15:47:01.517588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f997d1a99b6e'
down_revision: Union[str, None] = '617ffa2f1b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspecoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aberto_por_trigrama', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('concluido_por_trigrama', sa.String(length=10), nullable=True))
        batch_op.alter_column('data_inicio',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('tipos_inspecao', schema=None) as batch_op:
        batch_op.alter_column('duracao_dias',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_inspecao', schema=None) as batch_op:
        batch_op.alter_column('duracao_dias',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)

    with op.batch_alter_table('inspecoes', schema=None) as batch_op:
        batch_op.alter_column('data_inicio',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.drop_column('concluido_por_trigrama')
        batch_op.drop_column('aberto_por_trigrama')

    # ### end Alembic commands ###
