"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""Add SistemaAta

Revision ID: 48d0005f8339
Revises: ae1b32742c47
Create Date: 2026-05-05 19:08:27.781873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48d0005f8339'
down_revision: Union[str, None] = 'ae1b32742c47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistemas_ata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=10), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sistemas_ata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sistemas_ata_codigo'), ['codigo'], unique=True)

    with op.batch_alter_table('aeronaves', schema=None) as batch_op:
        batch_op.alter_column('horas_voo_total',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('data_inicio_operacao',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('panes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema_ata_id', sa.Uuid(), nullable=True, comment='Sistema ATA referenciado'))
        batch_op.create_index(batch_op.f('ix_panes_sistema_ata_id'), ['sistema_ata_id'], unique=False)
        batch_op.create_foreign_key('fk_panes_sistema_ata_id', 'sistemas_ata', ['sistema_ata_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('sistema_subsistema')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sistema_subsistema', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_panes_sistema_ata_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_panes_sistema_ata_id'))
        batch_op.drop_column('sistema_ata_id')

    with op.batch_alter_table('aeronaves', schema=None) as batch_op:
        batch_op.alter_column('data_inicio_operacao',
               existing_type=sa.DATE(),
               server_default=sa.text("'2020-01-01'"),
               existing_nullable=False)
        batch_op.alter_column('horas_voo_total',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0.0'"),
               existing_nullable=False)

    with op.batch_alter_table('sistemas_ata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sistemas_ata_codigo'))

    op.drop_table('sistemas_ata')
    # ### end Alembic commands ###
