"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""initial_schema

Revision ID: d6a790b729ac
Revises: 
Create Date: 2026-03-28 11:56:10.452314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a790b729ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronaves',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único universal da aeronave'),
    sa.Column('part_number', sa.String(length=50), nullable=True, comment='Part number da aeronave'),
    sa.Column('serial_number', sa.String(length=50), nullable=False, comment='Número de série único da aeronave'),
    sa.Column('matricula', sa.String(length=20), nullable=False, comment='Matrícula operacional (ex: 5900, 5901)'),
    sa.Column('modelo', sa.String(length=50), nullable=False, comment='Modelo da aeronave'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status operacional: OPERACIONAL | MANUTENCAO | INATIVA'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aeronaves_matricula'), 'aeronaves', ['matricula'], unique=True)
    op.create_index(op.f('ix_aeronaves_serial_number'), 'aeronaves', ['serial_number'], unique=True)
    op.create_table('equipamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False, comment='Nome do equipamento (ex: VUHF2, ELT, MDP)'),
    sa.Column('sistema', sa.String(length=50), nullable=True, comment='Sistema ao qual pertence (ex: COM, NAV, AP)'),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipamentos_part_number'), 'equipamentos', ['part_number'], unique=False)
    op.create_table('tipos_controle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('periodicidade_meses', sa.Integer(), nullable=False, comment='Intervalo em meses entre execuções do controle'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipos_controle_nome'), 'tipos_controle', ['nome'], unique=True)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único universal do usuário'),
    sa.Column('nome', sa.String(length=150), nullable=False, comment='Nome completo do militar'),
    sa.Column('posto', sa.String(length=30), nullable=False, comment='Posto ou graduação (ex: Ten, Cap, Sgt)'),
    sa.Column('especialidade', sa.String(length=50), nullable=True, comment='Especialidade técnica do militar'),
    sa.Column('funcao', sa.String(length=50), nullable=False, comment='Função no sistema: INSPETOR | ENCARREGADO | MANTENEDOR'),
    sa.Column('ramal', sa.String(length=20), nullable=True, comment='Ramal telefônico para contato'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nome de usuário único para login'),
    sa.Column('senha_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt da senha do usuário'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('equipamento_controles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipamento_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_controle_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_controle_id'], ['tipos_controle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('equipamento_id', 'tipo_controle_id', name='uq_equip_controle')
    )
    op.create_table('itens_equipamento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('equipamento_id', sa.Uuid(), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False, comment='Número de série único do item físico'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: ATIVO | ESTOQUE | REMOVIDO'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_equipamento_equipamento_id'), 'itens_equipamento', ['equipamento_id'], unique=False)
    op.create_index(op.f('ix_itens_equipamento_numero_serie'), 'itens_equipamento', ['numero_serie'], unique=True)
    op.create_table('panes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aeronave_id', sa.Uuid(), nullable=False, comment='Aeronave à qual a pane está vinculada (RN-01)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status da pane: ABERTA | EM_PESQUISA | RESOLVIDA'),
    sa.Column('sistema_subsistema', sa.String(length=100), nullable=True, comment='Sistema/subsistema onde a pane foi identificada'),
    sa.Column('descricao', sa.Text(), nullable=False, comment='Descrição detalhada da pane (RN-05)'),
    sa.Column('data_abertura', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False, comment='Data/hora de abertura automática (RN-08)'),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True, comment='Preenchido automaticamente ao concluir (RN-04)'),
    sa.Column('criado_por_id', sa.Uuid(), nullable=False, comment='Usuário que registrou a pane'),
    sa.Column('concluido_por_id', sa.Uuid(), nullable=True, comment='Usuário que concluiu a pane'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['concluido_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panes_aeronave_id'), 'panes', ['aeronave_id'], unique=False)
    op.create_index(op.f('ix_panes_status'), 'panes', ['status'], unique=False)
    op.create_table('anexos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pane_id', sa.Uuid(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False, comment='Caminho relativo ao diretório de uploads'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='IMAGEM | DOCUMENTO'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['pane_id'], ['panes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anexos_pane_id'), 'anexos', ['pane_id'], unique=False)
    op.create_table('controle_vencimentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_controle_id', sa.Uuid(), nullable=False),
    sa.Column('data_ultima_exec', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True, comment='Data calculada: data_ultima_exec + periodicidade_meses'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='OK | VENCENDO | VENCIDO'),
    sa.Column('origem', sa.String(length=20), nullable=False, comment='PADRAO (herdado) | ESPECIFICO (adicionado ao item)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens_equipamento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_controle_id'], ['tipos_controle.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'tipo_controle_id', name='uq_item_controle')
    )
    op.create_index(op.f('ix_controle_vencimentos_data_vencimento'), 'controle_vencimentos', ['data_vencimento'], unique=False)
    op.create_index(op.f('ix_controle_vencimentos_item_id'), 'controle_vencimentos', ['item_id'], unique=False)
    op.create_table('instalacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('aeronave_id', sa.Uuid(), nullable=False),
    sa.Column('data_instalacao', sa.Date(), nullable=False),
    sa.Column('data_remocao', sa.Date(), nullable=True, comment='NULL indica que o item ainda está instalado'),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['item_id'], ['itens_equipamento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instalacoes_aeronave_id'), 'instalacoes', ['aeronave_id'], unique=False)
    op.create_index(op.f('ix_instalacoes_item_id'), 'instalacoes', ['item_id'], unique=False)
    op.create_table('pane_responsaveis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pane_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('papel', sa.String(length=30), nullable=False, comment='Papel do responsável: INSPETOR | ENCARREGADO | MANTENEDOR'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['pane_id'], ['panes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pane_responsaveis_pane_id'), 'pane_responsaveis', ['pane_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pane_responsaveis_pane_id'), table_name='pane_responsaveis')
    op.drop_table('pane_responsaveis')
    op.drop_index(op.f('ix_instalacoes_item_id'), table_name='instalacoes')
    op.drop_index(op.f('ix_instalacoes_aeronave_id'), table_name='instalacoes')
    op.drop_table('instalacoes')
    op.drop_index(op.f('ix_controle_vencimentos_item_id'), table_name='controle_vencimentos')
    op.drop_index(op.f('ix_controle_vencimentos_data_vencimento'), table_name='controle_vencimentos')
    op.drop_table('controle_vencimentos')
    op.drop_index(op.f('ix_anexos_pane_id'), table_name='anexos')
    op.drop_table('anexos')
    op.drop_index(op.f('ix_panes_status'), table_name='panes')
    op.drop_index(op.f('ix_panes_aeronave_id'), table_name='panes')
    op.drop_table('panes')
    op.drop_index(op.f('ix_itens_equipamento_numero_serie'), table_name='itens_equipamento')
    op.drop_index(op.f('ix_itens_equipamento_equipamento_id'), table_name='itens_equipamento')
    op.drop_table('itens_equipamento')
    op.drop_table('equipamento_controles')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipos_controle_nome'), table_name='tipos_controle')
    op.drop_table('tipos_controle')
    op.drop_index(op.f('ix_equipamentos_part_number'), table_name='equipamentos')
    op.drop_table('equipamentos')
    op.drop_index(op.f('ix_aeronaves_serial_number'), table_name='aeronaves')
    op.drop_index(op.f('ix_aeronaves_matricula'), table_name='aeronaves')
    op.drop_table('aeronaves')
    # ### end Alembic commands ###
