"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_trigrama_to_usuarios

Revision ID: d04aaba36e56
Revises: 986779966fdc
Create Date: 2026-03-29 13:14:51.100205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04aaba36e56'
down_revision: Union[str, None] = '986779966fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('trigrama', sa.String(length=3), nullable=True, comment='Código de 3 letras que identifica o militar'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'trigrama')
    # ### end Alembic commands ###
