"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""desacoplamento_tarefas

Revision ID: 728522300c7e
Revises: 29bfac12c449
Create Date: 2026-04-30 12:59:13.498900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '728522300c7e'
down_revision: Union[str, None] = '29bfac12c449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarefas_catalogo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sistema', sa.String(length=100), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefas_catalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefas_catalogo_ativa'), ['ativa'], unique=False)

    with op.batch_alter_table('inspecao_tarefas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarefa_catalogo_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_inspecao_tarefas_tarefa_catalogo', 'tarefas_catalogo', ['tarefa_catalogo_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('tarefa_template_id')

    with op.batch_alter_table('tarefas_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarefa_catalogo_id', sa.Uuid(), nullable=False))
        batch_op.create_index(batch_op.f('ix_tarefas_template_tarefa_catalogo_id'), ['tarefa_catalogo_id'], unique=False)
        batch_op.create_unique_constraint('uq_tarefa_template_por_tipo', ['tipo_inspecao_id', 'tarefa_catalogo_id'])
        batch_op.create_foreign_key('fk_tarefas_template_tarefa_catalogo', 'tarefas_catalogo', ['tarefa_catalogo_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('descricao_padrao')
        batch_op.drop_column('sistema')
        batch_op.drop_column('titulo')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('sistema', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('descricao_padrao', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('uq_tarefa_template_por_tipo', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tarefas_template_tarefa_catalogo_id'))
        batch_op.drop_column('tarefa_catalogo_id')

    with op.batch_alter_table('inspecao_tarefas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tarefa_template_id', sa.CHAR(length=32), nullable=True))
        batch_op.create_foreign_key('fk_inspecao_tarefas_tarefa_template', 'tarefas_template', ['tarefa_template_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('tarefa_catalogo_id')

    with op.batch_alter_table('tarefas_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefas_catalogo_ativa'))

    op.drop_table('tarefas_catalogo')
    # ### end Alembic commands ###
