"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""Add TokenBlacklist table

Revision ID: 37195ef51f55
Revises: 2bbaf0779b57
Create Date: 2026-04-14 17:24:10.791701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37195ef51f55'
down_revision: Union[str, None] = '2bbaf0779b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=36), nullable=False, comment='JWT ID do token invalidado'),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False, comment='Data de expiração original do token. Útil para limpeza periódica da tabela.'),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))

    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
