"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_posicao_xlsx_to_slots_inventario

Revision ID: 994ef3b91511
Revises: d1e2f3a4b5c6
Create Date: 2026-05-12 17:11:50.098246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994ef3b91511'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.drop_index('ix_event_types_active')
        batch_op.drop_index('ix_event_types_name')
        batch_op.drop_index('ix_event_types_visibility_type')

    op.drop_table('event_types')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_events_created_by_user_id')
        batch_op.drop_index('ix_calendar_events_deleted_at')
        batch_op.drop_index('ix_calendar_events_deleted_by_user_id')
        batch_op.drop_index('ix_calendar_events_end_date')
        batch_op.drop_index('ix_calendar_events_event_type_id')
        batch_op.drop_index('ix_calendar_events_owner_user_id')
        batch_op.drop_index('ix_calendar_events_start_date')

    op.drop_table('calendar_events')
    with op.batch_alter_table('slots_inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posicao_xlsx', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_slots_inventario_posicao_xlsx'), ['posicao_xlsx'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slots_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slots_inventario_posicao_xlsx'))
        batch_op.drop_column('posicao_xlsx')

    op.create_table('calendar_events',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('owner_user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('event_type_id', sa.CHAR(length=32), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=False),
    sa.Column('end_date', sa.DATETIME(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('deleted_by_user_id', sa.CHAR(length=32), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='ck_calendar_events_period'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_events_start_date', ['start_date'], unique=False)
        batch_op.create_index('ix_calendar_events_owner_user_id', ['owner_user_id'], unique=False)
        batch_op.create_index('ix_calendar_events_event_type_id', ['event_type_id'], unique=False)
        batch_op.create_index('ix_calendar_events_end_date', ['end_date'], unique=False)
        batch_op.create_index('ix_calendar_events_deleted_by_user_id', ['deleted_by_user_id'], unique=False)
        batch_op.create_index('ix_calendar_events_deleted_at', ['deleted_at'], unique=False)
        batch_op.create_index('ix_calendar_events_created_by_user_id', ['created_by_user_id'], unique=False)

    op.create_table('event_types',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('visibility_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), nullable=False),
    sa.Column('private_color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=20), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint("visibility_type IN ('public', 'private')", name='ck_event_types_visibility_type'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.create_index('ix_event_types_visibility_type', ['visibility_type'], unique=False)
        batch_op.create_index('ix_event_types_name', ['name'], unique=1)
        batch_op.create_index('ix_event_types_active', ['active'], unique=False)

    # ### end Alembic commands ###
