"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_updated_at_audit_columns

Revision ID: 986779966fdc
Revises: dfb912f1f531
Create Date: 2026-03-29 12:12:37.457194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986779966fdc'
down_revision: Union[str, None] = 'dfb912f1f531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aeronaves', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    op.add_column('equipamentos', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    op.add_column('itens_equipamento', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    op.add_column('panes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    op.add_column('usuarios', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'updated_at')
    op.drop_column('panes', 'updated_at')
    op.drop_column('itens_equipamento', 'updated_at')
    op.drop_column('equipamentos', 'updated_at')
    op.drop_column('aeronaves', 'updated_at')
    # ### end Alembic commands ###
