"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_ativo_to_usuarios

Revision ID: fc37a9cf5271
Revises: d04aaba36e56
Create Date: 2026-03-30 17:30:47.860049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'fc37a9cf5271'
down_revision: Union[str, None] = 'd04aaba36e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Atualizar comentário de status de panes via batch (SQLite compatível)
    with op.batch_alter_table('panes') as batch:
        batch.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status da pane: ABERTA | RESOLVIDA',
               existing_comment='Status da pane: ABERTA | EM_PESQUISA | RESOLVIDA',
               existing_nullable=False)

    # Adicionar coluna 'ativo' com server_default para que rows existentes tenham valor
    with op.batch_alter_table('usuarios') as batch:
        batch.add_column(sa.Column('ativo', sa.Boolean(), nullable=False, server_default='1', comment='Controle de exclusão lógica (soft delete)'))
        batch.alter_column('funcao',
               existing_type=sa.VARCHAR(length=50),
               comment='Função no sistema: ADMINISTRADOR | ENCARREGADO | MANTENEDOR',
               existing_comment='Função no sistema: INSPETOR | ENCARREGADO | MANTENEDOR',
               existing_nullable=False)

    op.create_index(op.f('ix_usuarios_ativo'), 'usuarios', ['ativo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_ativo'), table_name='usuarios')
    with op.batch_alter_table('usuarios') as batch:
        batch.alter_column('funcao',
               existing_type=sa.VARCHAR(length=50),
               comment='Função no sistema: INSPETOR | ENCARREGADO | MANTENEDOR',
               existing_comment='Função no sistema: ADMINISTRADOR | ENCARREGADO | MANTENEDOR',
               existing_nullable=False)
        batch.drop_column('ativo')
    with op.batch_alter_table('panes') as batch:
        batch.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status da pane: ABERTA | EM_PESQUISA | RESOLVIDA',
               existing_comment='Status da pane: ABERTA | RESOLVIDA',
               existing_nullable=False)
    # ### end Alembic commands ###
