"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_periodicidade_meses_to_equipamento_controle

Revision ID: 802c031ae579
Revises: 213295655e96
Create Date: 2026-04-24 20:56:21.526866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '802c031ae579'
down_revision: Union[str, None] = '213295655e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento_controles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodicidade_meses', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento_controles', schema=None) as batch_op:
        batch_op.drop_column('periodicidade_meses')

    # ### end Alembic commands ###
