"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""inspecoes_tables_real

Revision ID: 29bfac12c449
Revises: 4cdf397899f3
Create Date: 2026-04-29 21:09:54.199520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bfac12c449'
down_revision: Union[str, None] = '4cdf397899f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipos_inspecao',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tipos_inspecao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_inspecao_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_tipos_inspecao_codigo'), ['codigo'], unique=True)

    op.create_table('inspecoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aeronave_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_abertura', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('aberto_por_id', sa.Uuid(), nullable=False),
    sa.Column('concluido_por_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aberto_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['concluido_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspecoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspecoes_aeronave_id'), ['aeronave_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspecoes_status'), ['status'], unique=False)

    op.create_table('tarefas_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo_inspecao_id', sa.Uuid(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao_padrao', sa.Text(), nullable=True),
    sa.Column('sistema', sa.String(length=100), nullable=True),
    sa.Column('obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tipo_inspecao_id'], ['tipos_inspecao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_inspecao_id', 'ordem', name='uq_tarefa_template_ordem_por_tipo')
    )
    with op.batch_alter_table('tarefas_template', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefas_template_tipo_inspecao_id'), ['tipo_inspecao_id'], unique=False)

    op.create_table('inspecao_evento_tipos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspecao_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_inspecao_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['inspecao_id'], ['inspecoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_inspecao_id'], ['tipos_inspecao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspecao_evento_tipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspecao_evento_tipos_inspecao_id'), ['inspecao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspecao_evento_tipos_tipo_inspecao_id'), ['tipo_inspecao_id'], unique=False)

    op.create_table('inspecao_tarefas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('inspecao_id', sa.Uuid(), nullable=False),
    sa.Column('tarefa_template_id', sa.Uuid(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sistema', sa.String(length=100), nullable=True),
    sa.Column('obrigatoria', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacao_execucao', sa.Text(), nullable=True),
    sa.Column('executado_por_id', sa.Uuid(), nullable=True),
    sa.Column('data_execucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pane_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['executado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inspecao_id'], ['inspecoes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pane_id'], ['panes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tarefa_template_id'], ['tarefas_template.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspecao_tarefas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspecao_tarefas_inspecao_id'), ['inspecao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspecao_tarefas_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspecao_tarefas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspecao_tarefas_status'))
        batch_op.drop_index(batch_op.f('ix_inspecao_tarefas_inspecao_id'))

    op.drop_table('inspecao_tarefas')
    with op.batch_alter_table('inspecao_evento_tipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspecao_evento_tipos_tipo_inspecao_id'))
        batch_op.drop_index(batch_op.f('ix_inspecao_evento_tipos_inspecao_id'))

    op.drop_table('inspecao_evento_tipos')
    with op.batch_alter_table('tarefas_template', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefas_template_tipo_inspecao_id'))

    op.drop_table('tarefas_template')
    with op.batch_alter_table('inspecoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspecoes_status'))
        batch_op.drop_index(batch_op.f('ix_inspecoes_aeronave_id'))

    op.drop_table('inspecoes')
    with op.batch_alter_table('tipos_inspecao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_inspecao_codigo'))
        batch_op.drop_index(batch_op.f('ix_tipos_inspecao_ativo'))

    op.drop_table('tipos_inspecao')
    # ### end Alembic commands ###
