"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""sync_models_reorganization

Revision ID: a572f9b3cbba
Revises: b2b0acbf451d
Create Date: 2026-04-22 11:21:40.211989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a572f9b3cbba'
down_revision: Union[str, None] = 'b2b0acbf451d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. Adiciona as colunas individualmente (fora do batch para evitar erro de dependência circular no SQLite)
    op.add_column('instalacoes', sa.Column('usuario_id', sa.Uuid(), nullable=True))
    op.add_column('instalacoes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))

    # 2. Adiciona a chave estrangeira usando o modo batch
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_instalacoes_usuario_id', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_instalacoes_usuario_id', type_='foreignkey')
    
    op.drop_column('instalacoes', 'created_at')
    op.drop_column('instalacoes', 'usuario_id')

    # ### end Alembic commands ###
