"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""initial_schema_consolidated

Revision ID: 6ff995143283
Revises: 
Create Date: 2026-04-18 22:33:30.756468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff995143283'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aeronaves',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único universal da aeronave'),
    sa.Column('part_number', sa.String(length=50), nullable=True, comment='Part number da aeronave'),
    sa.Column('serial_number', sa.String(length=50), nullable=False, comment='Número de série único da aeronave'),
    sa.Column('matricula', sa.String(length=20), nullable=False, comment='Matrícula operacional (ex: 5916, 5902)'),
    sa.Column('modelo', sa.String(length=50), nullable=False, comment='Modelo da aeronave'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status operacional: OPERACIONAL | MANUTENCAO | INATIVA'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aeronaves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aeronaves_matricula'), ['matricula'], unique=True)
        batch_op.create_index(batch_op.f('ix_aeronaves_serial_number'), ['serial_number'], unique=True)

    op.create_table('modelos_equipamento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('part_number', sa.String(length=50), nullable=False),
    sa.Column('nome_generico', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelos_equipamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modelos_equipamento_part_number'), ['part_number'], unique=True)

    op.create_table('tipos_controle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('periodicidade_meses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tipos_controle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipos_controle_nome'), ['nome'], unique=True)

    op.create_table('token_blacklist',
    sa.Column('jti', sa.String(length=36), nullable=False, comment='JWT ID do token invalidado'),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False, comment='Data de expiração original do token. Útil para limpeza periódica da tabela.'),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_blacklist_jti'), ['jti'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Identificador único universal do usuário'),
    sa.Column('nome', sa.String(length=150), nullable=False, comment='Nome completo do militar'),
    sa.Column('posto', sa.String(length=30), nullable=False, comment='Posto ou graduação (ex: Ten, Cap, Sgt)'),
    sa.Column('especialidade', sa.String(length=50), nullable=True, comment='Especialidade técnica do militar'),
    sa.Column('funcao', sa.String(length=50), nullable=False, comment='Função no sistema: ADMINISTRADOR | ENCARREGADO | MANTENEDOR'),
    sa.Column('ramal', sa.String(length=20), nullable=True, comment='Ramal telefônico para contato'),
    sa.Column('trigrama', sa.String(length=3), nullable=True, comment='Código de 3 letras que identifica o militar'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='Nome de usuário único para login'),
    sa.Column('senha_hash', sa.String(length=255), nullable=False, comment='Hash bcrypt da senha do usuário'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Controle de exclusão lógica (soft delete)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('equipamento_controles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modelo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_controle_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_equipamento.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_controle_id'], ['tipos_controle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo_id', 'tipo_controle_id', name='uq_equip_controle')
    )
    op.create_table('itens_equipamento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('modelo_id', sa.Uuid(), nullable=False),
    sa.Column('numero_serie', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_equipamento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modelo_id', 'numero_serie', name='uq_item_sn_per_pn')
    )
    with op.batch_alter_table('itens_equipamento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_equipamento_modelo_id'), ['modelo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_itens_equipamento_numero_serie'), ['numero_serie'], unique=False)

    op.create_table('panes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('aeronave_id', sa.Uuid(), nullable=False, comment='Aeronave à qual a pane está vinculada (RN-01)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status da pane: ABERTA | RESOLVIDA'),
    sa.Column('sistema_subsistema', sa.String(length=100), nullable=True, comment='Sistema/subsistema onde a pane foi identificada'),
    sa.Column('descricao', sa.Text(), nullable=False, comment='Descrição detalhada da pane (RN-05)'),
    sa.Column('data_abertura', sa.DateTime(timezone=True), nullable=False, comment='Data/hora de abertura automática (RN-08)'),
    sa.Column('data_conclusao', sa.DateTime(timezone=True), nullable=True, comment='Preenchido automaticamente ao concluir (RN-04)'),
    sa.Column('observacao_conclusao', sa.Text(), nullable=True, comment='Ação corretiva ou observações de conclusão'),
    sa.Column('comentarios', sa.Text(), nullable=True, comment='Comentários ou observações internas de manutenção'),
    sa.Column('ativo', sa.Boolean(), nullable=False, comment='Controle de exclusão lógica (soft delete)'),
    sa.Column('criado_por_id', sa.Uuid(), nullable=False, comment='Usuário que registrou a pane'),
    sa.Column('concluido_por_id', sa.Uuid(), nullable=True, comment='Usuário que concluiu a pane'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['concluido_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('panes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panes_aeronave_id'), ['aeronave_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_panes_ativo'), ['ativo'], unique=False)
        batch_op.create_index(batch_op.f('ix_panes_status'), ['status'], unique=False)

    op.create_table('slots_inventario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome_posicao', sa.String(length=100), nullable=False),
    sa.Column('sistema', sa.String(length=50), nullable=True),
    sa.Column('modelo_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_equipamento.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slots_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slots_inventario_nome_posicao'), ['nome_posicao'], unique=False)

    op.create_table('anexos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pane_id', sa.Uuid(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False, comment='Caminho relativo ao diretório de uploads'),
    sa.Column('tipo', sa.String(length=20), nullable=False, comment='IMAGEM | DOCUMENTO'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pane_id'], ['panes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anexos_pane_id'), ['pane_id'], unique=False)

    op.create_table('controle_vencimentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_controle_id', sa.Uuid(), nullable=False),
    sa.Column('data_ultima_exec', sa.Date(), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['itens_equipamento.id'], ),
    sa.ForeignKeyConstraint(['tipo_controle_id'], ['tipos_controle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'tipo_controle_id', name='uq_item_controle')
    )
    with op.batch_alter_table('controle_vencimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controle_vencimentos_data_vencimento'), ['data_vencimento'], unique=False)
        batch_op.create_index(batch_op.f('ix_controle_vencimentos_item_id'), ['item_id'], unique=False)

    op.create_table('instalacoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('aeronave_id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('data_instalacao', sa.Date(), nullable=False),
    sa.Column('data_remocao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['aeronave_id'], ['aeronaves.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens_equipamento.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots_inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instalacoes_aeronave_id'), ['aeronave_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instalacoes_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instalacoes_slot_id'), ['slot_id'], unique=False)

    op.create_table('pane_responsaveis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pane_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('papel', sa.String(length=30), nullable=False, comment='Papel do responsável: ADMINISTRADOR | ENCARREGADO | MANTENEDOR'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pane_id'], ['panes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pane_responsaveis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pane_responsaveis_pane_id'), ['pane_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pane_responsaveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pane_responsaveis_pane_id'))

    op.drop_table('pane_responsaveis')
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instalacoes_slot_id'))
        batch_op.drop_index(batch_op.f('ix_instalacoes_item_id'))
        batch_op.drop_index(batch_op.f('ix_instalacoes_aeronave_id'))

    op.drop_table('instalacoes')
    with op.batch_alter_table('controle_vencimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controle_vencimentos_item_id'))
        batch_op.drop_index(batch_op.f('ix_controle_vencimentos_data_vencimento'))

    op.drop_table('controle_vencimentos')
    with op.batch_alter_table('anexos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anexos_pane_id'))

    op.drop_table('anexos')
    with op.batch_alter_table('slots_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slots_inventario_nome_posicao'))

    op.drop_table('slots_inventario')
    with op.batch_alter_table('panes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panes_status'))
        batch_op.drop_index(batch_op.f('ix_panes_ativo'))
        batch_op.drop_index(batch_op.f('ix_panes_aeronave_id'))

    op.drop_table('panes')
    with op.batch_alter_table('itens_equipamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_equipamento_numero_serie'))
        batch_op.drop_index(batch_op.f('ix_itens_equipamento_modelo_id'))

    op.drop_table('itens_equipamento')
    op.drop_table('equipamento_controles')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_index(batch_op.f('ix_usuarios_ativo'))

    op.drop_table('usuarios')
    with op.batch_alter_table('token_blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_blacklist_jti'))

    op.drop_table('token_blacklist')
    with op.batch_alter_table('tipos_controle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipos_controle_nome'))

    op.drop_table('tipos_controle')
    with op.batch_alter_table('modelos_equipamento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelos_equipamento_part_number'))

    op.drop_table('modelos_equipamento')
    with op.batch_alter_table('aeronaves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aeronaves_serial_number'))
        batch_op.drop_index(batch_op.f('ix_aeronaves_matricula'))

    op.drop_table('aeronaves')
    # ### end Alembic commands ###
