"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_comentarios_to_panes

Revision ID: e7d64985f1b2
Revises: 37195ef51f55
Create Date: 2026-04-14 18:57:40.325516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d64985f1b2'
down_revision: Union[str, None] = '37195ef51f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentarios', sa.Text(), nullable=True, comment='Comentários ou observações internas de manutenção'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('panes', schema=None) as batch_op:
        batch_op.drop_column('comentarios')

    # ### end Alembic commands ###
