"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add pane observacao_conclusao and ativo

Revision ID: dfb912f1f531
Revises: 1e829a9c6428
Create Date: 2026-03-28 21:45:44.369586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfb912f1f531'
down_revision: Union[str, None] = '1e829a9c6428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panes', sa.Column('observacao_conclusao', sa.Text(), nullable=True, comment='Ação corretiva ou observações de conclusão'))
    op.add_column('panes', sa.Column('ativo', sa.Boolean(), nullable=False, server_default='true', comment='Controle de exclusão lógica (soft delete)'))
    op.create_index(op.f('ix_panes_ativo'), 'panes', ['ativo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_panes_ativo'), table_name='panes')
    op.drop_column('panes', 'ativo')
    op.drop_column('panes', 'observacao_conclusao')
    # ### end Alembic commands ###
