"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""Add indisponibilidades

Revision ID: 390dd051edd3
Revises: a52bed8e30b3
Create Date: 2026-04-26 20:05:27.162549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390dd051edd3'
down_revision: Union[str, None] = 'a52bed8e30b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indisponibilidades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indisponibilidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indisponibilidades_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indisponibilidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indisponibilidades_usuario_id'))

    op.drop_table('indisponibilidades')
    # ### end Alembic commands ###
