"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""Add technical fields to aircraft

Revision ID: ae1b32742c47
Revises: f997d1a99b6e
Create Date: 2026-05-03 16:19:26.265477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1b32742c47'
down_revision: Union[str, None] = 'f997d1a99b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aeronaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas_voo_total', sa.Float(), server_default='0.0', nullable=False, comment='Horas totais acumuladas da aeronave'))
        batch_op.add_column(sa.Column('data_inicio_operacao', sa.Date(), server_default='2020-01-01', nullable=False, comment='Data de início de operação da aeronave'))
        batch_op.add_column(sa.Column('horas_atualizadas_em', sa.DateTime(timezone=True), nullable=True, comment='Data e hora da última atualização das horas de voo'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aeronaves', schema=None) as batch_op:
        batch_op.drop_column('horas_atualizadas_em')
        batch_op.drop_column('data_inicio_operacao')
        batch_op.drop_column('horas_voo_total')

    # ### end Alembic commands ###
