"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""sync_models_reorganization

Revision ID: a572f9b3cbba
Revises: b2b0acbf451d
Create Date: 2026-04-22 11:21:40.211989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = 'a572f9b3cbba'
down_revision: Union[str, None] = 'b2b0acbf451d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    return column_name in {column["name"] for column in inspector.get_columns(table_name)}


def _has_foreign_key(table_name: str, constraint_name: str) -> bool:
    bind = op.get_bind()
    inspector = inspect(bind)
    return constraint_name in {
        foreign_key.get("name")
        for foreign_key in inspector.get_foreign_keys(table_name)
    }


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Esta migration pode encontrar bancos SQLite parcialmente atualizados.
    # Nesses casos, evita reaplicar colunas/FKs já presentes no schema.
    if not _has_column('instalacoes', 'usuario_id'):
        op.add_column('instalacoes', sa.Column('usuario_id', sa.Uuid(), nullable=True))
    if not _has_column('instalacoes', 'created_at'):
        op.add_column('instalacoes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # 2. Preenche a data para registros existentes
    op.execute("UPDATE instalacoes SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL")

    # 3. Agora sim recriamos a tabela via batch para aplicar NOT NULL e FK
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'))
        if not _has_foreign_key('instalacoes', 'fk_instalacoes_usuario_id'):
            batch_op.create_foreign_key('fk_instalacoes_usuario_id', 'usuarios', ['usuario_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        if _has_foreign_key('instalacoes', 'fk_instalacoes_usuario_id'):
            batch_op.drop_constraint('fk_instalacoes_usuario_id', type_='foreignkey')
        if _has_column('instalacoes', 'created_at'):
            batch_op.alter_column('created_at', nullable=True)

    if _has_column('instalacoes', 'created_at'):
        op.drop_column('instalacoes', 'created_at')
    if _has_column('instalacoes', 'usuario_id'):
        op.drop_column('instalacoes', 'usuario_id')

    # ### end Alembic commands ###
