"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_prorrogacao_vencimento

Revision ID: a52bed8e30b3
Revises: 802c031ae579
Create Date: 2026-04-25 20:04:11.675553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a52bed8e30b3'
down_revision: Union[str, None] = '802c031ae579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prorrogacoes_vencimento',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('controle_id', sa.Uuid(), nullable=False),
    sa.Column('numero_documento', sa.String(length=50), nullable=False),
    sa.Column('data_concessao', sa.Date(), nullable=False),
    sa.Column('data_nova_vencimento', sa.Date(), nullable=False),
    sa.Column('dias_adicionais', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('registrado_por_id', sa.Uuid(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['controle_id'], ['controle_vencimentos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prorrogacoes_vencimento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prorrogacoes_vencimento_controle_id'), ['controle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prorrogacoes_vencimento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prorrogacoes_vencimento_controle_id'))

    op.drop_table('prorrogacoes_vencimento')
    # ### end Alembic commands ###
