"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_inspecoes_module

Revision ID: bb4d91c20293
Revises: 0144b4b44e4a
Create Date: 2026-04-29 17:40:30.710325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4d91c20293'
down_revision: Union[str, None] = '0144b4b44e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
