"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add publicacoes_upload_jobs table

Revision ID: a16c12991b1b
Revises: b523f301e9f1
Create Date: 2026-08-08 12:12:07.872216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a16c12991b1b'
down_revision: Union[str, None] = 'b523f301e9f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publicacoes_upload_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rotulo', sa.String(length=20), nullable=False, comment="Rótulo da edição (ex: '2027')"),
    sa.Column('status', sa.Enum('ENVIANDO', 'PROCESSANDO', 'CONCLUIDO', 'FALHOU', 'CANCELADO', name='statusuploadjob'), nullable=False),
    sa.Column('etapa', sa.String(length=100), nullable=True, comment='Descrição da etapa atual'),
    sa.Column('progresso_pct', sa.Integer(), nullable=False, comment='Progresso de 0 a 100%'),
    sa.Column('erro', sa.Text(), nullable=True, comment='Mensagem de erro detalhada quando FALHOU'),
    sa.Column('file_key', sa.String(length=500), nullable=False, comment='Caminho/Key do ZIP no Storage'),
    sa.Column('upload_id_r2', sa.String(length=200), nullable=True, comment='UploadID multipart no S3/R2 ou local'),
    sa.Column('tamanho_declarado', sa.BigInteger(), nullable=False, comment='Tamanho declarado em bytes'),
    sa.Column('edicao_id', sa.Uuid(), nullable=True),
    sa.Column('criado_por_id', sa.Uuid(), nullable=False),
    sa.Column('processo_pid', sa.Integer(), nullable=True, comment='PID do subprocesso worker'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['edicao_id'], ['manuais_edicoes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publicacoes_upload_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publicacoes_upload_jobs_status'), ['status'], unique=False)
        batch_op.create_index('uq_publicacoes_upload_jobs_ativo_unico', ['status'], unique=True, sqlite_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"), postgresql_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"))

    with op.batch_alter_table('equipamento_controles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipamento_controles', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    with op.batch_alter_table('publicacoes_upload_jobs', schema=None) as batch_op:
        batch_op.drop_index('uq_publicacoes_upload_jobs_ativo_unico', sqlite_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"), postgresql_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"))
        batch_op.drop_index(batch_op.f('ix_publicacoes_upload_jobs_status'))

    op.drop_table('publicacoes_upload_jobs')
    # ### end Alembic commands ###
