"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_ativo_to_usuarios

Revision ID: fc37a9cf5271
Revises: d04aaba36e56
Create Date: 2026-03-30 17:30:47.860049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc37a9cf5271'
down_revision: Union[str, None] = 'd04aaba36e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('panes', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status da pane: ABERTA | RESOLVIDA',
               existing_comment='Status da pane: ABERTA | EM_PESQUISA | RESOLVIDA',
               existing_nullable=False)
    op.add_column('usuarios', sa.Column('ativo', sa.Boolean(), nullable=True, comment='Controle de exclusão lógica (soft delete)'))
    op.execute("UPDATE usuarios SET ativo = TRUE")
    op.alter_column('usuarios', 'ativo', nullable=False)
    op.alter_column('usuarios', 'funcao',
               existing_type=sa.VARCHAR(length=50),
               comment='Função no sistema: ADMINISTRADOR | ENCARREGADO | MANTENEDOR',
               existing_comment='Função no sistema: INSPETOR | ENCARREGADO | MANTENEDOR',
               existing_nullable=False)
    op.create_index(op.f('ix_usuarios_ativo'), 'usuarios', ['ativo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_ativo'), table_name='usuarios')
    op.alter_column('usuarios', 'funcao',
               existing_type=sa.VARCHAR(length=50),
               comment='Função no sistema: INSPETOR | ENCARREGADO | MANTENEDOR',
               existing_comment='Função no sistema: ADMINISTRADOR | ENCARREGADO | MANTENEDOR',
               existing_nullable=False)
    op.drop_column('usuarios', 'ativo')
    op.alter_column('panes', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='Status da pane: ABERTA | EM_PESQUISA | RESOLVIDA',
               existing_comment='Status da pane: ABERTA | RESOLVIDA',
               existing_nullable=False)
    # ### end Alembic commands ###
