"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""remove_periodicidade_from_tipos_controle

Revision ID: 213295655e96
Revises: a572f9b3cbba
Create Date: 2026-04-24 20:40:59.960484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213295655e96'
down_revision: Union[str, None] = 'a572f9b3cbba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('tipos_controle', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_column('periodicidade_meses')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_controle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periodicidade_meses', sa.INTEGER(), nullable=False))
        batch_op.alter_column('nome',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    # ### end Alembic commands ###
