"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""initial_schema

Revision ID: 1e829a9c6428
Revises: d6a790b729ac
Create Date: 2026-03-28 13:52:40.168260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e829a9c6428'
down_revision: Union[str, None] = 'd6a790b729ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
