"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_updated_at_to_instalacoes

Revision ID: 0d5cbfc8249b
Revises: 6ff995143283
Create Date: 2026-04-19 19:21:36.415677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5cbfc8249b'
down_revision: Union[str, None] = '6ff995143283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instalacoes', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
