"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""update publicacoes_upload_jobs single flight index

Revision ID: dc6bbdf4335a
Revises: a16c12991b1b
Create Date: 2026-08-08 12:40:05.567742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc6bbdf4335a'
down_revision: Union[str, None] = 'a16c12991b1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacoes_upload_jobs', schema=None) as batch_op:
        batch_op.drop_index('uq_publicacoes_upload_jobs_ativo_unico', sqlite_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"))
        batch_op.create_index('uq_publicacoes_upload_jobs_ativo_unico', [sa.text('1')], unique=True, sqlite_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"), postgresql_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publicacoes_upload_jobs', schema=None) as batch_op:
        batch_op.drop_index('uq_publicacoes_upload_jobs_ativo_unico', sqlite_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"), postgresql_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"))
        batch_op.create_index('uq_publicacoes_upload_jobs_ativo_unico', ['status'], unique=1, sqlite_where=sa.text("status IN ('ENVIANDO', 'PROCESSANDO')"))

    # ### end Alembic commands ###
