"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add duration and dpe fields to inspections

Revision ID: 617ffa2f1b86
Revises: 728522300c7e
Create Date: 2026-05-02 15:10:08.702702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617ffa2f1b86'
down_revision: Union[str, None] = '728522300c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspecoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
        batch_op.add_column(sa.Column('data_fim_prevista', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('tarefas_template', schema=None) as batch_op:
        batch_op.alter_column('tarefa_catalogo_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    with op.batch_alter_table('tipos_inspecao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duracao_dias', sa.Integer(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tipos_inspecao', schema=None) as batch_op:
        batch_op.drop_column('duracao_dias')

    with op.batch_alter_table('tarefas_template', schema=None) as batch_op:
        batch_op.alter_column('tarefa_catalogo_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('inspecoes', schema=None) as batch_op:
        batch_op.drop_column('data_fim_prevista')
        batch_op.drop_column('data_inicio')

    # ### end Alembic commands ###
