"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_updated_at_audit_columns

Revision ID: 986779966fdc
Revises: dfb912f1f531
Create Date: 2026-03-29 12:12:37.457194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986779966fdc'
down_revision: Union[str, None] = 'dfb912f1f531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Usar batch_alter_table para compatibilidade com SQLite
    with op.batch_alter_table('aeronaves') as batch:
        batch.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    with op.batch_alter_table('equipamentos') as batch:
        batch.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    with op.batch_alter_table('itens_equipamento') as batch:
        batch.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    with op.batch_alter_table('panes') as batch:
        batch.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    with op.batch_alter_table('usuarios') as batch:
        batch.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Atualizado automaticamente em cada modificação'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios') as batch:
        batch.drop_column('updated_at')
    with op.batch_alter_table('panes') as batch:
        batch.drop_column('updated_at')
    with op.batch_alter_table('itens_equipamento') as batch:
        batch.drop_column('updated_at')
    with op.batch_alter_table('equipamentos') as batch:
        batch.drop_column('updated_at')
    with op.batch_alter_table('aeronaves') as batch:
        batch.drop_column('updated_at')
    # ### end Alembic commands ###
