"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""add_account_lockout_fields

Revision ID: b2b0acbf451d
Revises: a1b2c3d4e5f6
Create Date: 2026-04-20 13:36:55.357686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b0acbf451d'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0', comment='Contador de tentativas de login falhas consecutivas'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Se preenchido, a conta está bloqueada até este horário'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')
    # ### end Alembic commands ###
