"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""Add executado_por_id

Revision ID: 0144b4b44e4a
Revises: 390dd051edd3
Create Date: 2026-04-28 20:13:49.715136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0144b4b44e4a'
down_revision: Union[str, None] = '390dd051edd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controle_vencimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executado_por_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_controle_vencimentos_exec_por', 'usuarios', ['executado_por_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controle_vencimentos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_controle_vencimentos_exec_por', type_='foreignkey')
        batch_op.drop_column('executado_por_id')

    # ### end Alembic commands ###
