"""add_token_refresh_table

Revision ID: a1b2c3d4e5f6
Revises: 0d5cbfc8249b
Create Date: 2026-04-19 23:00:00.000000

Sprint 2.1: Add TokenRefresh model for storing refresh tokens with 7-day expiry
and revocation tracking for token rotation mechanism.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '0d5cbfc8249b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'token_refresh',
        sa.Column('id', sa.Uuid(), nullable=False, comment='ID único do refresh token'),
        sa.Column('usuario_id', sa.Uuid(), nullable=False, comment='Referência ao usuário'),
        sa.Column('jti', sa.String(length=36), nullable=False, comment='JWT ID do refresh token (para rastreamento)'),
        sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False, comment='Data de expiração do refresh token (7 dias)'),
        sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
        sa.Column('revogado_em', sa.DateTime(timezone=True), nullable=True, comment='Se preenchido, o token foi revogado'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('jti')
    )
    with op.batch_alter_table('token_refresh', schema=None) as batch_op:
        batch_op.create_index('ix_token_refresh_usuario_id', ['usuario_id'], unique=False)
        batch_op.create_index('ix_token_refresh_jti', ['jti'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_refresh', schema=None) as batch_op:
        batch_op.drop_index('ix_token_refresh_jti')
        batch_op.drop_index('ix_token_refresh_usuario_id')

    op.drop_table('token_refresh')
    # ### end Alembic commands ###
