"""
migrations/script.py.mako
Template para geração de scripts de migração pelo Alembic.
"""

"""inspecoes_tables

Revision ID: 4cdf397899f3
Revises: bb4d91c20293
Create Date: 2026-04-29 21:08:47.317388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cdf397899f3'
down_revision: Union[str, None] = 'bb4d91c20293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
